#!/bin/sh

# from Jeff Schaller on stackoverflow, thanks Jeff!
find_config() {
  if [ -d "$1" ]; then
    echo "${PWD%/}/$1"
  elif [ "$PWD" = / ]; then
    false
  else
    (cd .. && find_config "$1") # subshell so we don't affect caller's $PWD
  fi
}
wimp_dir="$(find_config ".wimp")"

service_name=$(echo $wimp_dir | openssl md5 | awk '{print $2 "-wimp.service"}')
if ! [ -f "/etc/systemd/system/$service_name" ]; then
  touch /etc/systemd/system/$service_name
fi
echo "[Unit]
Description=Run wimp website generator

[Service]
Type=simple
ExecStart=sh -c \"inotifywait -qmre modify -e delete --format \\\"%e %w%f\\\" $wimp_dir/../src/ |\
while read inotifymessage; do
  filepath=\\\${inotifymessage##* }
  outpath=\\\"\\\${filepath%.md}.html\\\"; outpath=\\\"$wimp_dir/../public/\\\${outpath##*src/}\\\"
  if [ \\\"\\\${inotifymessage%% *}\\\" = DELETE ]; then rm -rf \\\$outpath
  else sh -c 'if ! [ -d \\\"\\\${1%/*}\\\" ]; then mkdir \\\"\\\${1%/*}\\\"; fi
  pandoc --quiet -s \\\"\\\$0\" -o \\\"\\\$1\\\"' \\\$filepath \\\$outpath; fi
done\"
Restart=on-failure

[Install]
WantedBy=default.target" > /etc/systemd/system/$service_name
sudo systemctl daemon-reload; sudo systemctl enable $service_name
